---
language: python
python: "3.6"

install:
    - pip install ansible
    - ansible --version
    - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
    - echo "This build is used only to trigger an import in galaxy"

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/